[package]
name = "nevr"
version = "0.1.0"
edition = "2024"

[dependencies]
vulkano = "0.35.1"
vulkano-shaders = "0.35.0"
winit = { version = "0.30.11", features = ["rwh_06"] }
glam = "0.30.4"
bytemuck = "1.23.1"
