[package]
name = "nevr"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = "1.23.2"
bevy = { git = "https://github.com/bevyengine/bevy.git", default-features = false, features = ["wayland", "x11", "bevy_core_pipeline", "bevy_render", "bevy_winit", "std"] }
